# Configuration for GoReleaser
# https://goreleaser.com/

version: 2

project_name: prometheus-lvm-exporter

builds:
  - main: .
    binary: prometheus-lvm-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - -trimpath
    ldflags: |
      -s -w
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      -X github.com/prometheus/common/version.Branch={{.Branch}}
      -X github.com/prometheus/common/version.BuildDate={{.Date}}

nfpms:
  - description: Prometheus exporter for LVM metrics
    maintainer: M. Hanselmann
    bindir: /usr/sbin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    dependencies:
      - lvm2
    contents:
      - src: ./README.md
        dst: /usr/share/doc/prometheus-lvm-exporter/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/prometheus-lvm-exporter/LICENSE
      - src: contrib/systemd/prometheus-lvm-exporter.service
        dst: /lib/systemd/system/prometheus-lvm-exporter.service
      - src: contrib/systemd/prometheus-lvm-exporter.default
        dst: /etc/default/prometheus-lvm-exporter
        type: config

    scripts:
      postinstall: "contrib/postinstall.sh"
      preremove: "contrib/preremove.sh"
      postremove: "contrib/postremove.sh"

archives:
  - formats:
      - tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

changelog:
  groups:
    - title: Dependencies
      regexp: '(?i)^(?:[a-f0-9]{8,64}\s+)?Bump\s+[-.\w]+/\w.*\sto\s'
      order: 1
    - order: 0

release:
  draft: true
  prerelease: auto

snapshot:
  version_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
